[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/api/*"
  to = "https://attendancesystem-8hfa.onrender.com/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/socket.io/*"
  to = "https://attendancesystem-8hfa.onrender.com/socket.io/:splat"
  status = 200
  force = true
  headers = { Connection = "upgrade" }
